version: '2'

services:
  #php and Nginx
  web:
    build: php_nginx
    ports:
      - "80:80"
    volumes:
      - ./../laravel/:/var/www/laravel/
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      PHP_IDE_CONFIG: "serverName=gundamkid.docker"
    container_name: gundamkid_laravel_stack